###

GET http://localhost:8082/api/users/alex/champions

###

GET http://localhost:8082/api/users/adam/champions/2

###

GET http://localhost:8082/api/champions

###

GET http://localhost:8082/api/champions/2

###

GET http://localhost:8082/api/races

###

GET http://localhost:8082/api/races/bard

###

POST http://localhost:8082/api/users/norman/champions
Content-Type: application/json

{
  "name": "rob",
  "backstory": "noone",
  "manaPoints": "500",
  "healthPoints": "700",
  "strength": "6",
  "inteligence": "9",
  "race": "troll"
}

###

POST http://localhost:8082/api/champions
Content-Type: application/json

{
  "name": "bardon",
  "backstory": "Teenager from big city where he needed to get by using his musical abilities",
  "manaPoints": "200",
  "healthPoints": "900",
  "strength": "5",
  "inteligence": "14",
  "race": "bard"
}

###

POST http://localhost:8082/api/races
Content-Type: application/json

{
  "name": "ork",
  "description": "Big angry creatures who are destroying everything on their way"
}

###

PUT http://localhost:8082/api/users/adam/champions/2
Content-Type: application/json

{
  "name": "someone",
  "backstory": "none",
  "manaPoints": "23",
  "healthPoints": "23",
  "strength": "23",
  "inteligence": "23",
  "race": null
}

###

PUT http://localhost:8082/api/champions/2
Content-Type: application/json

{
  "name": "Herold",
  "backstory": "Powerfull herold",
  "experience": 1000
}

###

PUT http://localhost:8082/api/races/bard
Content-Type: application/json

{
  "description": "no one"
}

###

DELETE http://localhost:8082/api/users/adam/champions/2

###

DELETE http://localhost:8082/api/champions/2

###

DELETE http://localhost:8082/api/races/sorcerer

###